### ISSUE TITLE
Hung up on connect

### ISSUE THREAD

**Issue by ohsayan** [sfackler/tokio-openssl#26]
I'm trying to use `tokio_openssl` to write to a server, but unfortunately things hang up when calling `connect()`:
```rust
        let mut connector = SslConnector::builder(SslMethod::tls())?;
        connector.set_ca_file(sslcert)?;
        let ssl = connector.build().configure()?.into_ssl(&domain)?;
        let stream = TcpStream::connect(host).await?;
        let mut stream = SslStream::new(ssl, stream)?;
        Pin::new(&mut stream).connect().await?; // This is the offending line
        println!("Connect to bls://{}", host);
```

**Comment by sfackler** [comment]
You may want to use something like wireshark to look at the traffic, or create a complete, self contained example of what's going on that I can look at.

**Comment by ohsayan** [comment]
Hey Steven,
I'll take a look and report back.

Thanks,
Sayan
________________________________

**Comment by ohsayan** [comment]
Hey there,
I managed to do a bit of sniffing, and here's what I got:
![Screenshot from 2021-01-12 12-48-57](https://user-images.githubusercontent.com/17377258/104282342-e8c5a900-54d4-11eb-8330-7418b49fd2b5.png)
The last packet that you can see is where the program freezes (like I mentioned above)

**Comment by sfackler** [comment]
That looks like the client is sending its hello to the server, and the server never responds.

**Comment by ohsayan** [comment]
Precisely; looks like it's an issue with the server and not this library. 

Thank you for your time,
Sayan
