### ISSUE TITLE
tokio-openssl seems to be not working

### ISSUE THREAD

**Issue by cemoktra** [sfackler/tokio-openssl#28]
I added async streams to my project but SSL fails now.
https://github.com/cemoktra/ice-rs/blob/main/src/ssl.rs

I cannot send any bytes to the stream

**Comment by sfackler** [comment]
If you do not provide any information at all about *how* it seems to be not working, I can't help you.

**Comment by cemoktra** [comment]
Therefore I posted the link to the source.

Basically I wrap it around a Tokio TCP stream and split the stream into read and write half. When I try to send any bytes, nothing happens

**Comment by sfackler** [comment]
You may need to call [connect](https://docs.rs/tokio-openssl/0.6.1/tokio_openssl/struct.SslStream.html#method.connect) before being able to read and write.

I would expect read/write calls to be returning errors if that does not happen. For example, if you remove the [this line](https://github.com/sfackler/tokio-openssl/blob/master/src/test.rs#L23) from the test that connects to google.com, the following error is returned:

```
test test::google ... FAILED

failures:

---- test::google stdout ----
thread 'test::google' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337690900, library: "SSL routines", function: "ssl_write_internal", reason: "uninitialized", file: "ssl/ssl_lib.c", line: 1921 }]))) } }', src/test.rs:24:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by cemoktra** [comment]
Oh yes i'm missing the connect after switching to async. But now i get the following on the connect call, and the other end of the connection receives something wrong

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 336130315, library: "SSL routines", function: "ssl3_get_record", reason: "wrong version number", file: "../ssl/record/ssl3_record.c", line: 331 }]))) }', /home/bazz-dee/programming/ice/ice-rs/src/ssl.rs:108:57
```

**Comment by cemoktra** [comment]
Ok, setting server to TSL1_3 fixes this problem
