### ISSUE TITLE
API request

### ISSUE THREAD

**Issue by wongsyrone** [sfackler/tokio-openssl#29]
Hi,

Can you please add these APIs for OpenSSL 1.1.1?

https://docs.rs/openssl/0.10.33/openssl/ssl/struct.SslStream.html#method.read_early_data
https://docs.rs/openssl/0.10.33/openssl/ssl/struct.SslStream.html#method.write_early_data
https://docs.rs/openssl/0.10.33/openssl/ssl/struct.SslStream.html#method.stateless

**Comment by sfackler** [comment]
I don't understand. Those APIs are already defined for OpenSSL 1.1.1 - you linked to their documentation!

**Comment by wongsyrone** [comment]
I mean add these functions to https://github.com/sfackler/tokio-openssl/blob/master/src/lib.rs#L105 and wrap them into `poll_*` and pub async functions

**Comment by sfackler** [comment]
Oh! Sorry, I totally missed that this was the tokio-openssl repo, not the rust-openssl repo D:

**Comment by sfackler** [comment]
SSL_stateless may not be so straightforward to expose an async interface over:

> For SSL_stateless() if an entire ClientHello message cannot be read without the "read" BIO becoming empty then the SSL_stateless() call will fail. It is the application's responsibility to ensure that data read from the "read" BIO during a single SSL_stateless() call is all from the same peer.

https://www.openssl.org/docs/manmaster/man3/SSL_stateless.html

**Comment by sfackler** [comment]
https://github.com/sfackler/tokio-openssl/pull/30

**Comment by wongsyrone** [comment]
Thanks.
