### ISSUE TITLE
Feature request: impl AsyncBufRead

### ISSUE THREAD

**Issue by wongsyrone** [sfackler/tokio-openssl#34]
Hi, can you please implement https://docs.rs/tokio/1.7.1/tokio/io/trait.AsyncBufRead.html? It would be better to have read_line(), lines(), etc.

**Comment by sfackler** [comment]
I don't believe OpenSSL provides raw access to its internal buffer. If you need an AsyncBufRead implementation, you can wrap SslStream in a BufReader.
