### ISSUE TITLE
Question: Why is there no tokio_openssl::accept since version 0.6?

### ISSUE THREAD

**Issue by jannik4** [sfackler/tokio-openssl#38]
I need this function to accept an asynchronous TCP stream on an `openssl::ssl::SslAcceptor`. Is this no longer possible or has this feature moved somewhere else?

**Comment by sfackler** [comment]
https://docs.rs/tokio-openssl/latest/tokio_openssl/struct.SslStream.html#method.accept

**Comment by jannik4** [comment]
Oh, thank you. Just found it in the tests as well.

(I thought the SslStream was just for the `openssl::ssl::SslStream`. Didn't know how to get there from the `openssl::ssl::SslAcceptor`).
