### ISSUE TITLE
How does do_handshake().await be waked?

### ISSUE THREAD

**Issue by iamwwc** [sfackler/tokio-openssl#40]
I found cx pass into `poll_do_handshake`

https://github.com/sfackler/tokio-openssl/blob/df062b7d2d0b548090d2ec4ec4fa4ccb530a61fc/src/lib.rs#L147

but `s.do_handshake()` don't pass cx down.  
```rs
pub fn poll_do_handshake(
        self: Pin<&mut Self>,
        cx: &mut Context<'_>,
    ) -> Poll<Result<(), ssl::Error>> {
        // we lose cx when call s.do_handshake
        self.with_context(cx, |s| cvt_ossl(s.do_handshake()))
    }
```
If cx don't reregister into tokio scheduler, `do_handshake().await` will never give us Poll::Ready

How does tokio-openssl handle this problem? I don't know why we need `with_context`
Thank you :)

**Comment by sfackler** [comment]
We need with_context because it is the thing that passes cx down. https://github.com/sfackler/tokio-openssl/blob/master/src/lib.rs#L210

**Comment by iamwwc** [comment]
> We need with_context because it is the thing that passes cx down. https://github.com/sfackler/tokio-openssl/blob/master/src/lib.rs#L210

I can't get it. how with_context passes cx down. I can only see 

```rs
// put at .context
this.0.get_mut().context = ctx as *mut _ as usize;
let r = f(&mut this.0);
// reset context to zero
this.0.get_mut().context = 0;
```

I have read all codes, I don't see where cx be passed down

**Comment by sfackler** [comment]
The context is stored in the `context` field there, and retrieved here https://github.com/sfackler/tokio-openssl/blob/master/src/lib.rs#L40

**Comment by iamwwc** [comment]
> The context is stored in the `context` field there, and retrieved here https://github.com/sfackler/tokio-openssl/blob/master/src/lib.rs#L40

only read, write have a call to `parts`. not `async fn do_handshake`. how `do_handshake` passes cx down?

![image](https://user-images.githubusercontent.com/24750337/192517790-c10476a0-0fbd-442c-9702-2e76c5f169d2.png)

**Comment by sfackler** [comment]
`do_handshake` will call read and write.

**Comment by iamwwc** [comment]
> `do_handshake` will call read and write.

where `do_handshake` call read/write? I can only see `do_handshake` directly call into `SSL_do_handshake`, no read/write called
from
https://github.com/sfackler/tokio-openssl/blob/df062b7d2d0b548090d2ec4ec4fa4ccb530a61fc/src/lib.rs#L142
call into
https://github.com/sfackler/rust-openssl/blob/e43eb58540b27a17f8029c397e3edc12bbc9011f/openssl/src/ssl/mod.rs#L3325

**Comment by sfackler** [comment]
`SSL_do_handshake` calls read and write.
