### ISSUE TITLE
Unclean disconnects leave peer in the lurch

### ISSUE THREAD

**Issue by FreeMasen** [sfackler/tokio-openssl#41]
If the peer connection cannot successfully close its connection cleanly, the empty buffer indicating a close has occurred is never received.

[Here is a minimal reproduction of the problem](https://github.com/FreeMasen/tokio-openssl-hanging-close-minimal-repro)

**Comment by sfackler** [comment]
Using mem::forget acts exactly as if you had just kept the stream around without reading or writing to it. It is not disconnecting. What behavior do you think should be happening in this case?

**Comment by dljsjr** [comment]
@sfackler Robert and I are actually looking at this together. The context here is that I'm working with a TLS-secured Server Sent Event stream from a Philips Hue bridge. Because the client doesn't write to this stream and is just waiting for the occassional message, if the remote end hangs up the stream is permanently pending and waits around forever.

**Comment by FreeMasen** [comment]
Thank you for the quick reply!

Sorry for the bad reproduction, I will attempt to update it to actually model what I am experiencing which is that read is yielding forever when the close doesn't happen cleanly.

**Comment by sfackler** [comment]
If the peer is abruptly disconnected in that kind of way and the local client is only reading the kernel won't know that the peer is gone. TCP keepalive is one mechanism to help discover that the connection is dead. An alternative approach is to just read with a timeout and treat a lack of data for a certain period of time for any reason as a problem (e.g. using https://docs.rs/tokio/latest/tokio/time/fn.timeout.html).

**Comment by dljsjr** [comment]
> TCP keepalive is one mechanism to help discover that the connection is dead

I've tried this and it doesn't seem to remediate anything

> An alternative approach is to just read with a timeout and treat a lack of data for a certain period of time for any reason as a problem

This isn't the best heuristic because the SSE stream can go minutes without sending anything.

**Comment by sfackler** [comment]
> I've tried this and it doesn't seem to remediate anything

What was your keepalive configuration? It defaults to polling after 2 hours of idleness IIRC.

You can use a tool like wireshark to listen on the TCP traffic between your client and the remote server.

**Comment by dljsjr** [comment]
> > I've tried this and it doesn't seem to remediate anything
> 
> What was your keepalive configuration? It defaults to polling after 2 hours of idleness IIRC.
> 
> You can use a tool like wireshark to listen on the TCP traffic between your client and the remote server.

Mea culpa, I didn't have a good TCP Keepalive configuration. I set the time and the retries but not the interval. Thanks for your patience on that @sfackler. I think that's doing what I need it to do but I need to do some in-situ tests as well.

**Comment by FreeMasen** [comment]
@sfackler Thank you again for all your feedback/support! The keep-alive configuration ended up being the issue we were encountering.
